# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combineddialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 800))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.tabWidget = QtWidgets.QTabWidget(MainWindow)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        self.tabWidget.setDocumentMode(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(1280, 800))
        self.tabWidget.setMaximumSize(QtCore.QSize(1280, 800))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.txtEID = QtWidgets.QLineEdit(self.tab)
        self.txtEID.setGeometry(QtCore.QRect(210, 80, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.txtEID.setFont(font)
        self.txtEID.setAlignment(QtCore.Qt.AlignCenter)
        self.txtEID.setObjectName("txtEID")
        self.lblClock = QtWidgets.QLabel(self.tab)
        self.lblClock.setGeometry(QtCore.QRect(10, 80, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lblClock.setFont(font)
        self.lblClock.setAlignment(QtCore.Qt.AlignCenter)
        self.lblClock.setObjectName("lblClock")
        self.txtWOID = QtWidgets.QLineEdit(self.tab)
        self.txtWOID.setGeometry(QtCore.QRect(210, 170, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.txtWOID.setFont(font)
        self.txtWOID.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWOID.setObjectName("txtWOID")
        self.lblWOID = QtWidgets.QLabel(self.tab)
        self.lblWOID.setGeometry(QtCore.QRect(10, 170, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lblWOID.setFont(font)
        self.lblWOID.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWOID.setObjectName("lblWOID")
        self.btnStart = QtWidgets.QPushButton(self.tab)
        self.btnStart.setGeometry(QtCore.QRect(70, 270, 311, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btnStart.setFont(font)
        self.btnStart.setObjectName("btnStart")
        self.btnStop = QtWidgets.QPushButton(self.tab)
        self.btnStop.setGeometry(QtCore.QRect(70, 430, 311, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btnStop.setFont(font)
        self.btnStop.setObjectName("btnStop")
        self.btnClear = QtWidgets.QPushButton(self.tab)
        self.btnClear.setGeometry(QtCore.QRect(70, 590, 311, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.lcdTime = QtWidgets.QLCDNumber(self.tab)
        self.lcdTime.setGeometry(QtCore.QRect(460, 10, 241, 81))
        self.lcdTime.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdTime.setObjectName("lcdTime")
        self.rbIndirect = QtWidgets.QRadioButton(self.tab)
        self.rbIndirect.setGeometry(QtCore.QRect(880, 280, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.rbIndirect.setFont(font)
        self.rbIndirect.setObjectName("rbIndirect")
        self.rbWeld = QtWidgets.QRadioButton(self.tab)
        self.rbWeld.setGeometry(QtCore.QRect(560, 410, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.rbWeld.setFont(font)
        self.rbWeld.setObjectName("rbWeld")
        self.rbFinal = QtWidgets.QRadioButton(self.tab)
        self.rbFinal.setGeometry(QtCore.QRect(880, 150, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.rbFinal.setFont(font)
        self.rbFinal.setIconSize(QtCore.QSize(16, 16))
        self.rbFinal.setObjectName("rbFinal")
        self.rbShipReceive = QtWidgets.QRadioButton(self.tab)
        self.rbShipReceive.setGeometry(QtCore.QRect(880, 410, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.rbShipReceive.setFont(font)
        self.rbShipReceive.setObjectName("rbShipReceive")
        self.rbAssembly = QtWidgets.QRadioButton(self.tab)
        self.rbAssembly.setGeometry(QtCore.QRect(560, 280, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.rbAssembly.setFont(font)
        self.rbAssembly.setObjectName("rbAssembly")
        self.rbFab = QtWidgets.QRadioButton(self.tab)
        self.rbFab.setGeometry(QtCore.QRect(560, 150, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.rbFab.setFont(font)
        self.rbFab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rbFab.setObjectName("rbFab")
        self.rbMaterialHandling = QtWidgets.QRadioButton(self.tab)
        self.rbMaterialHandling.setGeometry(QtCore.QRect(880, 530, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.rbMaterialHandling.setFont(font)
        self.rbMaterialHandling.setObjectName("rbMaterialHandling")
        self.rbElectric = QtWidgets.QRadioButton(self.tab)
        self.rbElectric.setGeometry(QtCore.QRect(560, 650, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.rbElectric.setFont(font)
        self.rbElectric.setObjectName("rbElectric")
        self.rbPaint = QtWidgets.QRadioButton(self.tab)
        self.rbPaint.setGeometry(QtCore.QRect(560, 530, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.rbPaint.setFont(font)
        self.rbPaint.setObjectName("rbPaint")
        self.rbLab = QtWidgets.QRadioButton(self.tab)
        self.rbLab.setGeometry(QtCore.QRect(880, 650, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.rbLab.setFont(font)
        self.rbLab.setObjectName("rbLab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btn5 = QtWidgets.QPushButton(self.tab_2)
        self.btn5.setGeometry(QtCore.QRect(920, 210, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn5.setFont(font)
        self.btn5.setObjectName("btn5")
        self.txtClockID = QtWidgets.QLineEdit(self.tab_2)
        self.txtClockID.setGeometry(QtCore.QRect(340, 120, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.txtClockID.setFont(font)
        self.txtClockID.setAlignment(QtCore.Qt.AlignCenter)
        self.txtClockID.setObjectName("txtClockID")
        self.btnClearParts = QtWidgets.QPushButton(self.tab_2)
        self.btnClearParts.setGeometry(QtCore.QRect(80, 590, 251, 141))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btnClearParts.setFont(font)
        self.btnClearParts.setObjectName("btnClearParts")
        self.lblQty = QtWidgets.QLabel(self.tab_2)
        self.lblQty.setGeometry(QtCore.QRect(600, 290, 141, 91))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.lblQty.setFont(font)
        self.lblQty.setText("")
        self.lblQty.setAlignment(QtCore.Qt.AlignCenter)
        self.lblQty.setObjectName("lblQty")
        self.lblPartReturn = QtWidgets.QLabel(self.tab_2)
        self.lblPartReturn.setGeometry(QtCore.QRect(20, 440, 581, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblPartReturn.setFont(font)
        self.lblPartReturn.setText("")
        self.lblPartReturn.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPartReturn.setObjectName("lblPartReturn")
        self.btn8 = QtWidgets.QPushButton(self.tab_2)
        self.btn8.setGeometry(QtCore.QRect(920, 330, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn8.setFont(font)
        self.btn8.setObjectName("btn8")
        self.lblWOBOMID = QtWidgets.QLabel(self.tab_2)
        self.lblWOBOMID.setGeometry(QtCore.QRect(0, 270, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lblWOBOMID.setFont(font)
        self.lblWOBOMID.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWOBOMID.setObjectName("lblWOBOMID")
        self.btn4 = QtWidgets.QPushButton(self.tab_2)
        self.btn4.setGeometry(QtCore.QRect(790, 210, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn4.setFont(font)
        self.btn4.setObjectName("btn4")
        self.lblWOIDReturn = QtWidgets.QLabel(self.tab_2)
        self.lblWOIDReturn.setGeometry(QtCore.QRect(20, 350, 581, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblWOIDReturn.setFont(font)
        self.lblWOIDReturn.setText("")
        self.lblWOIDReturn.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWOIDReturn.setObjectName("lblWOIDReturn")
        self.btn7 = QtWidgets.QPushButton(self.tab_2)
        self.btn7.setGeometry(QtCore.QRect(790, 330, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn7.setFont(font)
        self.btn7.setObjectName("btn7")
        self.txtWOBOMID = QtWidgets.QLineEdit(self.tab_2)
        self.txtWOBOMID.setGeometry(QtCore.QRect(340, 260, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.txtWOBOMID.setFont(font)
        self.txtWOBOMID.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWOBOMID.setObjectName("txtWOBOMID")
        self.lblClockID = QtWidgets.QLabel(self.tab_2)
        self.lblClockID.setGeometry(QtCore.QRect(0, 130, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lblClockID.setFont(font)
        self.lblClockID.setAlignment(QtCore.Qt.AlignCenter)
        self.lblClockID.setObjectName("lblClockID")
        self.btn1 = QtWidgets.QPushButton(self.tab_2)
        self.btn1.setGeometry(QtCore.QRect(790, 90, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setObjectName("btn1")
        self.btn6 = QtWidgets.QPushButton(self.tab_2)
        self.btn6.setGeometry(QtCore.QRect(1050, 210, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn6.setFont(font)
        self.btn6.setObjectName("btn6")
        self.btnClearQty = QtWidgets.QPushButton(self.tab_2)
        self.btnClearQty.setGeometry(QtCore.QRect(920, 450, 241, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btnClearQty.setFont(font)
        self.btnClearQty.setObjectName("btnClearQty")
        self.btn3 = QtWidgets.QPushButton(self.tab_2)
        self.btn3.setGeometry(QtCore.QRect(1050, 90, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn3.setFont(font)
        self.btn3.setObjectName("btn3")
        self.btn0 = QtWidgets.QPushButton(self.tab_2)
        self.btn0.setGeometry(QtCore.QRect(790, 450, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn0.setFont(font)
        self.btn0.setObjectName("btn0")
        self.btnEnter = QtWidgets.QPushButton(self.tab_2)
        self.btnEnter.setGeometry(QtCore.QRect(560, 590, 611, 141))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btnEnter.setFont(font)
        self.btnEnter.setObjectName("btnEnter")
        self.btn2 = QtWidgets.QPushButton(self.tab_2)
        self.btn2.setGeometry(QtCore.QRect(920, 90, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn2.setFont(font)
        self.btn2.setObjectName("btn2")
        self.btn9 = QtWidgets.QPushButton(self.tab_2)
        self.btn9.setGeometry(QtCore.QRect(1050, 330, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn9.setFont(font)
        self.btn9.setObjectName("btn9")
        self.lcdTimeParts = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdTimeParts.setGeometry(QtCore.QRect(450, 10, 261, 81))
        self.lcdTimeParts.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdTimeParts.setObjectName("lcdTimeParts")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Freeman Labor Tracker"))
        self.lblClock.setText(_translate("MainWindow", "Clock #"))
        self.lblWOID.setText(_translate("MainWindow", "WO #"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.btnClear.setText(_translate("MainWindow", "Clear"))
        self.rbIndirect.setText(_translate("MainWindow", "Indirect"))
        self.rbWeld.setText(_translate("MainWindow", "Weld"))
        self.rbFinal.setText(_translate("MainWindow", "Final"))
        self.rbShipReceive.setText(_translate("MainWindow", "Ship/Receive"))
        self.rbAssembly.setText(_translate("MainWindow", "Assembly"))
        self.rbFab.setText(_translate("MainWindow", "Fab"))
        self.rbMaterialHandling.setText(_translate("MainWindow", "Material Handling"))
        self.rbElectric.setText(_translate("MainWindow", "Electric"))
        self.rbPaint.setText(_translate("MainWindow", "Paint"))
        self.rbLab.setText(_translate("MainWindow", "Lab"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Labor Tracker"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btnClearParts.setText(_translate("MainWindow", "Clear"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.lblWOBOMID.setText(_translate("MainWindow", "WO BOM #"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.lblClockID.setText(_translate("MainWindow", "Clock #"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btnClearQty.setText(_translate("MainWindow", "Clear"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btnEnter.setText(_translate("MainWindow", "Enter"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Parts Issuing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

